version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    labels:
      - "rag.ollama"
    entrypoint: |
      /bin/sh -c "
        ollama serve & \
        sleep 10 && \
        ollama pull all-minilm && \
        ollama pull mistral:7b && \
        wait"

  api:
    build:
      context: .  # Build context (the folder with your Dockerfile)
      args:
        API_IMAGE: ""
    image: ${API_IMAGE}
    container_name: api
    environment:
      - APP_MODULE=main:app
    ports:
      - "8000:8000"
    labels:
      - "rag.api"
    entrypoint: /bin/sh -c "sleep 90 && exec uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - ollama